name: todoapp

networks:
  network:
    driver: bridge
    name: todoapp-net
services:
  app:
    image: todoapp:2.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=Development
    networks:
      - network
    depends_on:
      - mysql-db
    restart: unless-stopped
  mysql-db:
    image: mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - network
volumes:
  db-volume:
    name: todoapp-db-volume
